name: Compile 

on: [push, workflow_dispatch]

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Create document
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Convert to pdf
      id: convert-to-pdf
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        latexmk_use_xelatex: true
    - name: Store pdf
      uses: actions/upload-artifact@v2
      with:
        name: main.pdf
        path: main.pdf
